version: "2"

services:
  node-db:
    image: postgres:11.21-alpine
    ports:
      - "5432:5432"
    volumes:
      - node-db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: node
      PGDATA: "/var/lib/postgresql/data"
    container_name: node-db
    restart: on-failure
volumes:
  node-db:
