CREATE TABLE edge
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    source_id      BIGINT,
    destination_id BIGINT,
    weight         INTEGER                                 NOT NULL,
    CONSTRAINT pk_edge PRIMARY KEY (id)
);

CREATE TABLE node
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_node PRIMARY KEY (id)
);

ALTER TABLE edge
    ADD CONSTRAINT FK_EDGE_ON_DESTINATION FOREIGN KEY (destination_id) REFERENCES node (id);

ALTER TABLE edge
    ADD CONSTRAINT FK_EDGE_ON_SOURCE FOREIGN KEY (source_id) REFERENCES node (id);

INSERT INTO node (name)
VALUES ('Алматы'),
       ('Караганда'),
       ('Астана'),
       ('Шымкент'),
       ('Актобе'),
       ('Атырау'),
       ('Уральск'),
       ('Костанай'),
       ('Актау'),
       ('Павлодар'),
       ('Семей'),
       ('Усть-Каменогорск');

-- Вставка рёбер между городами с двусторонними маршрутами
INSERT INTO edge (source_id, destination_id, weight)
VALUES ((SELECT id FROM node WHERE name = 'Алматы'), (SELECT id FROM node WHERE name = 'Караганда'), 999),
       ((SELECT id FROM node WHERE name = 'Караганда'), (SELECT id FROM node WHERE name = 'Алматы'), 999),

       ((SELECT id FROM node WHERE name = 'Алматы'), (SELECT id FROM node WHERE name = 'Астана'), 1200),
       ((SELECT id FROM node WHERE name = 'Астана'), (SELECT id FROM node WHERE name = 'Алматы'), 1200),

       ((SELECT id FROM node WHERE name = 'Караганда'), (SELECT id FROM node WHERE name = 'Астана'), 200),
       ((SELECT id FROM node WHERE name = 'Астана'), (SELECT id FROM node WHERE name = 'Караганда'), 200),

       ((SELECT id FROM node WHERE name = 'Алматы'), (SELECT id FROM node WHERE name = 'Шымкент'), 700),
       ((SELECT id FROM node WHERE name = 'Шымкент'), (SELECT id FROM node WHERE name = 'Алматы'), 700),

       ((SELECT id FROM node WHERE name = 'Шымкент'), (SELECT id FROM node WHERE name = 'Актобе'), 900),
       ((SELECT id FROM node WHERE name = 'Актобе'), (SELECT id FROM node WHERE name = 'Шымкент'), 900),

       ((SELECT id FROM node WHERE name = 'Актобе'), (SELECT id FROM node WHERE name = 'Атырау'), 600),
       ((SELECT id FROM node WHERE name = 'Атырау'), (SELECT id FROM node WHERE name = 'Актобе'), 600),

       ((SELECT id FROM node WHERE name = 'Актобе'), (SELECT id FROM node WHERE name = 'Уральск'), 400),
       ((SELECT id FROM node WHERE name = 'Уральск'), (SELECT id FROM node WHERE name = 'Актобе'), 400),

       ((SELECT id FROM node WHERE name = 'Астана'), (SELECT id FROM node WHERE name = 'Костанай'), 800),
       ((SELECT id FROM node WHERE name = 'Костанай'), (SELECT id FROM node WHERE name = 'Астана'), 800),

       ((SELECT id FROM node WHERE name = 'Атырау'), (SELECT id FROM node WHERE name = 'Актау'), 1300),
       ((SELECT id FROM node WHERE name = 'Актау'), (SELECT id FROM node WHERE name = 'Атырау'), 1300),

       ((SELECT id FROM node WHERE name = 'Костанай'), (SELECT id FROM node WHERE name = 'Павлодар'), 500),
       ((SELECT id FROM node WHERE name = 'Павлодар'), (SELECT id FROM node WHERE name = 'Костанай'), 500),

       ((SELECT id FROM node WHERE name = 'Павлодар'), (SELECT id FROM node WHERE name = 'Семей'), 300),
       ((SELECT id FROM node WHERE name = 'Семей'), (SELECT id FROM node WHERE name = 'Павлодар'), 300),

       ((SELECT id FROM node WHERE name = 'Семей'), (SELECT id FROM node WHERE name = 'Усть-Каменогорск'), 150),
       ((SELECT id FROM node WHERE name = 'Усть-Каменогорск'), (SELECT id FROM node WHERE name = 'Семей'), 150);
